version: 2.1
workflows:
  ci_pipeline_only:
    jobs:
      - ci-pipeline
  scheduled_ci_cd_pipeline:
    triggers:
      - schedule:
          # Runs every Sunday at 8PM
          cron: "0 20 * * 0"
          filters:
            branches:
              only:
                - main
    jobs:
      - ci-pipeline
      - cd-pipeline:
          requires:
              - ci-pipeline

jobs:
  ci-pipeline:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Build CI/CD and webapp docker image"
          command: ./build_steps/ci.sh build
      - run:
          name: "Run postgres and redis databases"
          command: ./build_steps/ci.sh start_db
      - run:
          name: "Run unit tests"
          command: ./build_steps/ci.sh unit_tests
      - run:
          name: "Run pre commit hooks (linting)"
          command: ./build_steps/ci.sh lint
      - run:
          name: "Run webapp container and check health"
          command: ./build_steps/ci.sh healthcheck
      - run:
          name: "Stop and remove all containers"
          command: ./build_steps/ci.sh clean
      - run:
          name: "Publish images to Dockerhub"
          command: ./build_steps/ci.sh push_images
      - run:
          name: "Push variables to ssm paramter store for CD pipeline"
          command: ./build_steps/ci.sh put_ssm_vars
  cd-pipeline:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Create AWS infrastructure
          no_output_timeout: 30m
          command: set -e; ENVIRONMENT=dev make cfn-create
      - run:
          name: Deploy application to AWS
          command: set -e; ENVIRONMENT=dev make deploy
      - run:
          name: Load Testing application
          command: make load-testing
      - run:
          name: Delete AWS infrastructure
          command: ENVIRONMENT=dev make cfn-delete-async
