version: 2.1
workflows:
  ci_pipeline_only:
    jobs:
      - ci-pipeline
  scheduled_ci_cd_pipeline:
    triggers:
      - schedule:
          # Runs every Sunday at 8PM
          cron: "0 20 * * 0"
          filters:
            branches:
              only:
                - main
    jobs:
      - ci-pipeline
      - cd-pipeline:
          requires:
              - ci-pipeline

jobs:
  ci-pipeline:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Build CI/CD docker image"
          command: set -e; make build-image-cicd-if-not-exists
      - run:
          name: "Build webapp docker image"
          command: set -e; make build-image-webapp-if-not-exists
      - run:
          name: "Run postgres and redis databases"
          command: set -e; make db-up
      - run:
          name: "Run unit tests"
          command: set -e; make tests
      - run:
          name: "Run pre commit hooks (linting)"
          command: set -e; make lint
      - run:
          name: "Run webapp container and check health"
          command: set -e; make healthcheck
      - run:
          name: "Stop and remove database containers"
          command: set -e; make db-down
      - run:
          name: "Publish images to Dockerhub"
          command: set -e; make publish-images
      - run:
          name: "Push variables to ssm paramter store for CD pipeline"
          command: set -e; make put-image-name-to-ssm
  cd-pipeline:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Create AWS infrastructure
          no_output_timeout: 30m
          command: set -e; ENVIRONMENT=dev make cfn-create
      - run:
          name: Deploy application to AWS
          command: set -e; ENVIRONMENT=dev make deploy
      - run:
          name: Load Testing application
          command: make load-testing
      - run:
          name: Delete AWS infrastructure
          command: ENVIRONMENT=dev make cfn-delete-async
