version: 2.1
workflows:
  main_workflow:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install Packages
          command: sudo apt update; sudo apt-get install -y jq curl wget gcc libpq-dev python3-dev
      - run:
          name: Set Conda and Poetry paths
          command: echo "export PATH=$HOME/miniconda/bin:$HOME/.poetry/bin:$PATH" >> $BASH_ENV
      - restore_cache:
          keys:
          - libs-{{ checksum "poetry.lock" }}-2
      - run:
          name: Install Miniconda
          command: |
            if [ ! -d "$HOME/miniconda" ]; then
              wget "https://repo.anaconda.com/miniconda/Miniconda3-4.7.10-Linux-x86_64.sh" -O $HOME/miniconda.sh
              printf '%s' "8a324adcc9eaf1c09e22a992bb6234d91a94146840ee6b11c114ecadafc68121  miniconda.sh" | sha256sum -c
              bash $HOME/miniconda.sh -b -p $HOME/miniconda
            else
                echo "Miniconda is already installed, continuing to build."
            fi
      - run:
          name: Install Poetry
          command: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - run:
          name: Install dependencies
          command: |
            conda update -y conda
            if ! conda info --envs | grep django-on-aws; then
              make env
            else
              echo "conda environment django-on-aws already exists"
              make env-update
            fi
      - save_cache:
          paths:
            - /home/circleci/miniconda/
          key: libs-{{ checksum "poetry.lock" }}-2
      - run: make tests
      - run: make image
      - run: make up
      - run: make healthcheck
      - run: make down
      - run: make publish
      - run: make cfn-package
      - run: make cfn-validate
      # - run: make cfn-create
      # - run: make deploy
      # - run: make load-testing
      # - run: make cfn-delete
