version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: scripts/1_stop_server.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/2_before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/3_after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/4_start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/5_validate_service.sh
      timeout: 300
  
